apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.qbittorrent.name }}-config-pv-claim
spec:
  storageClassName: nfs-csi-applications
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi