{{- if .Values.qbittorrent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.qbittorrent.name }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
  {{- with .Values.qbittorrent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}