{{- if .Values.nodered.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.nodered.name }}-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - hosts:
        - {{ .Values.nodered.ingress.localHostname }}
      secretName: home-pheliperocha-com-staging-tls
  rules:
    - host: {{ .Values.nodered.ingress.localHostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.nodered.name }}-service
                port:
                  number: 1880
{{- end }}