{{- if .Values.nodered.enabled }}
{{- if .Values.nodered.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nodered.name }}
  labels:
    {{- include "nodered.labels" . | nindent 4 }}
  {{- with .Values.nodered.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}