{{- if .Values.nodered.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodered.name }}-service
  labels:
    {{- include "nodered.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 1880
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nodered.selectorLabels" . | nindent 4 }}
{{- end }}