apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.qbittorrent.name }}-config-pv-claim
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
