{{- if .Values.k8up.manualBackup }}
apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: manual-backup
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
  {{- with .Values.k8up.backend }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}