{{- if .Values.nfs.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-applications
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.12
  share: /vol/nfs/applications
  subDir: "${pvc.metadata.name}"
  mountPermissions: "0777"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
{{- end }}