apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-pvc
  annotations:
    k8up.io/backup: "false"
spec:
  storageClassName: nfs-csi-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 800Gi