apiVersion: v2
name: grafana
description: A Helm chart for Grafana
type: application
version: 0.1.0
appVersion: "1.0.0"
sources:
  - https://github.com/pheliperocha/home-server
  - https://github.com/pheliperocha/home-server/tree/main/kube/grafana
maintainers:
  - name: Phelipe Rocha
    url: https://pheliperocha.com
dependencies:
  - name: grafana
    version: "8.10.1"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled