grafana:
  enabled: true
  name: grafana
  admin:
    existingSecret: grafana-secrets
    userKey: ADMIN_USER
    passwordKey: ADMIN_PASSWORD
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        url: http://loki-gateway.grafana.svc.cluster.local.