version: '3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'portainer_data:/data'
    ports:
      - '8000:8000'
      - '9443:9443'
      - '9000:9000'

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - homeassistant_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8123:8123/tcp"
    restart: unless-stopped
    privileged: true
    healthcheck:
      test: curl --fail http://localhost:8123 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    links:
      - homeassistant
  
  cloudflare_homeassistant_tunnel:
    container_name: cloudflare_homeassistant_tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --protocol http2 --no-autoupdate --metrics localhost:3333 run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    links:
      - homeassistant

volumes:
  portainer_data:
    name: portainer_data
    external: true

  homeassistant_config:
    name: homeassistant_config
    external: true

  node_red_data:
    name: node_red_data
    external: true