homeassistant:
  name: homeassistant
  replicaCount: 1
  serviceAccount:
    create: true
    annotations: {}

nodered:
  name: nodered
  replicaCount: 1
  serviceAccount:
    create: true
    annotations: {}