{{- if .Values.context_flow.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.context_flow.name }}-api-service
  labels:
    {{- include "context_flow.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.context_flow.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.context_flow.name }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}