{{- if .Values.context_flow.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.context_flow.name }}-serviceaccount
  labels:
    {{- include "context_flow.labels" . | nindent 4 }}
{{- end }}