{{- if .Values.drone_launcher.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.drone_launcher.name }}-finance-project-staging
  namespace: finance-project-staging
subjects:
  - kind: ServiceAccount
    name: {{ .Values.drone_launcher.name }}-serviceaccount
    namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.drone_launcher.name }}-clusterrole
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.drone_launcher.name }}-finance-project-production
  namespace: finance-project-production
subjects:
  - kind: ServiceAccount
    name: {{ .Values.drone_launcher.name }}-serviceaccount
    namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.drone_launcher.name }}-clusterrole
{{- end }}