{{- if .Values.drone_launcher.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.drone_launcher.name }}-clusterrole
  labels:
    {{- include "drone_launcher.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - serviceaccounts
      - configmaps
      - services
      - pods
    verbs:
      - list
      - get
      - create
      - update
      - delete
      - patch

  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
      - create
      - patch
      - delete

  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - get
      - create
      - patch
      - delete
{{- end }}