grafana-k8s-monitoring:
  enabled: true

k8s-monitoring:
  cluster:
    name: minikube
  destinations:
    - name: grafana-cloud-metrics
      type: prometheus
      url: https://prometheus-prod-40-prod-sa-east-1.grafana.net/api/prom/push
      auth:
        type: basic
        username: "2341921"
        password: glc_eyJvIjoiMTM4NDc4OSIsIm4iOiJzdGFjay0xMjA4ODQxLWludGVncmF0aW9uLWt1YmVybmV0ZXMtZ3JhZmFuYS1hbGxveS1rdWJlcm5ldGVzLWdyYWZhbmEtYWxsb3kiLCJrIjoiVXE5eTBnUEQyWk5YODhsNzNqQXA5Zjk3IiwibSI6eyJyIjoicHJvZC1zYS1lYXN0LTEifX0=
    - name: grafana-cloud-logs
      type: loki
      url: https://logs-prod-024.grafana.net/loki/api/v1/push
      auth:
        type: basic
        username: "1166638"
        password: glc_eyJvIjoiMTM4NDc4OSIsIm4iOiJzdGFjay0xMjA4ODQxLWludGVncmF0aW9uLWt1YmVybmV0ZXMtZ3JhZmFuYS1hbGxveS1rdWJlcm5ldGVzLWdyYWZhbmEtYWxsb3kiLCJrIjoiVXE5eTBnUEQyWk5YODhsNzNqQXA5Zjk3IiwibSI6eyJyIjoicHJvZC1zYS1lYXN0LTEifX0=
    - name: grafana-cloud-traces
      type: otlp
      url: https://tempo-prod-17-prod-sa-east-1.grafana.net:443
      protocol: grpc
      auth:
        type: basic
        username: "1160952"
        password: glc_eyJvIjoiMTM4NDc4OSIsIm4iOiJzdGFjay0xMjA4ODQxLWludGVncmF0aW9uLWt1YmVybmV0ZXMtZ3JhZmFuYS1hbGxveS1rdWJlcm5ldGVzLWdyYWZhbmEtYWxsb3kiLCJrIjoiVXE5eTBnUEQyWk5YODhsNzNqQXA5Zjk3IiwibSI6eyJyIjoicHJvZC1zYS1lYXN0LTEifX0=
      metrics:
        enabled: false
      logs:
        enabled: false
      traces:
        enabled: true
  clusterMetrics:
    enabled: true
    opencost:
      enabled: true
      metricsSource: grafana-cloud-metrics
      opencost:
        exporter:
          defaultClusterId: minikube
        prometheus:
          existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
          external:
            url: https://prometheus-prod-40-prod-sa-east-1.grafana.net/api/prom
    kepler:
      enabled: true
  clusterEvents:
    enabled: true
  podLogs:
    enabled: true
  applicationObservability:
    enabled: true
    receivers:
      otlp:
        grpc:
          enabled: true
          port: 4317
        http:
          enabled: true
          port: 4318
      zipkin:
        enabled: true
        port: 9411
  alloy-metrics:
    enabled: true
    alloy:
      extraEnv:
        - name: GCLOUD_RW_API_KEY
          valueFrom:
            secretKeyRef:
              name: alloy-metrics-remote-cfg-grafana-k8s-monitoring
              key: password
        - name: CLUSTER_NAME
          value: minikube
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: GCLOUD_FM_COLLECTOR_ID
          value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
    remoteConfig:
      enabled: true
      url: https://fleet-management-prod-015.grafana.net
      auth:
        type: basic
        username: "1208841"
        password: glc_eyJvIjoiMTM4NDc4OSIsIm4iOiJzdGFjay0xMjA4ODQxLWludGVncmF0aW9uLWt1YmVybmV0ZXMtZ3JhZmFuYS1hbGxveS1rdWJlcm5ldGVzLWdyYWZhbmEtYWxsb3kiLCJrIjoiVXE5eTBnUEQyWk5YODhsNzNqQXA5Zjk3IiwibSI6eyJyIjoicHJvZC1zYS1lYXN0LTEifX0=
  alloy-singleton:
    enabled: true
    alloy:
      extraEnv:
        - name: GCLOUD_RW_API_KEY
          valueFrom:
            secretKeyRef:
              name: alloy-singleton-remote-cfg-grafana-k8s-monitoring
              key: password
        - name: CLUSTER_NAME
          value: minikube
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: GCLOUD_FM_COLLECTOR_ID
          value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
    remoteConfig:
      enabled: true
      url: https://fleet-management-prod-015.grafana.net
      auth:
        type: basic
        username: "1208841"
        password: glc_eyJvIjoiMTM4NDc4OSIsIm4iOiJzdGFjay0xMjA4ODQxLWludGVncmF0aW9uLWt1YmVybmV0ZXMtZ3JhZmFuYS1hbGxveS1rdWJlcm5ldGVzLWdyYWZhbmEtYWxsb3kiLCJrIjoiVXE5eTBnUEQyWk5YODhsNzNqQXA5Zjk3IiwibSI6eyJyIjoicHJvZC1zYS1lYXN0LTEifX0=
  alloy-logs:
    enabled: true
    alloy:
      extraEnv:
        - name: GCLOUD_RW_API_KEY
          valueFrom:
            secretKeyRef:
              name: alloy-logs-remote-cfg-grafana-k8s-monitoring
              key: password
        - name: CLUSTER_NAME
          value: minikube
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: GCLOUD_FM_COLLECTOR_ID
          value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-logs-$(NODE_NAME)
    remoteConfig:
      enabled: true
      url: https://fleet-management-prod-015.grafana.net
      auth:
        type: basic
        username: "1208841"
        password: glc_eyJvIjoiMTM4NDc4OSIsIm4iOiJzdGFjay0xMjA4ODQxLWludGVncmF0aW9uLWt1YmVybmV0ZXMtZ3JhZmFuYS1hbGxveS1rdWJlcm5ldGVzLWdyYWZhbmEtYWxsb3kiLCJrIjoiVXE5eTBnUEQyWk5YODhsNzNqQXA5Zjk3IiwibSI6eyJyIjoicHJvZC1zYS1lYXN0LTEifX0=
  alloy-receiver:
    enabled: true
    alloy:
      extraPorts:
        - name: otlp-grpc
          port: 4317
          targetPort: 4317
          protocol: TCP
        - name: otlp-http
          port: 4318
          targetPort: 4318
          protocol: TCP
        - name: zipkin
          port: 9411
          targetPort: 9411
          protocol: TCP
      extraEnv:
        - name: GCLOUD_RW_API_KEY
          valueFrom:
            secretKeyRef:
              name: alloy-receiver-remote-cfg-grafana-k8s-monitoring
              key: password
        - name: CLUSTER_NAME
          value: minikube
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: GCLOUD_FM_COLLECTOR_ID
          value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-receiver-$(NODE_NAME)
    remoteConfig:
      enabled: true
      url: https://fleet-management-prod-015.grafana.net
      auth:
        type: basic
        username: "1208841"
        password: glc_eyJvIjoiMTM4NDc4OSIsIm4iOiJzdGFjay0xMjA4ODQxLWludGVncmF0aW9uLWt1YmVybmV0ZXMtZ3JhZmFuYS1hbGxveS1rdWJlcm5ldGVzLWdyYWZhbmEtYWxsb3kiLCJrIjoiVXE5eTBnUEQyWk5YODhsNzNqQXA5Zjk3IiwibSI6eyJyIjoicHJvZC1zYS1lYXN0LTEifX0=