{{- if .Values.kuma.enabled }}
{{- if .Values.kuma.tunnel.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "tunnel-{{ .Values.kuma.name }}"
  labels:
    {{- include "kuma.labels" . | nindent 4 }}
    tunnel: "tunnel-{{ .Values.kuma.name }}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "tunnel-{{ .Values.kuma.name }}"
      app.kubernetes.io/instance: {{ .Release.Name }}
      tunnel: "tunnel-{{ .Values.kuma.name }}"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "tunnel-{{ .Values.kuma.name }}"
        app.kubernetes.io/instance: {{ .Release.Name }}
        tunnel: "tunnel-{{ .Values.kuma.name }}"
    spec:
      containers:
      - name: "tunnel-{{ .Values.kuma.name }}"
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        # Points cloudflared to the config file, which configures what
        # cloudflared will actually do. This file is created by a ConfigMap
        # below.
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        livenessProbe:
          httpGet:
            # Cloudflared has a /ready endpoint which returns 200 if and only if
            # it has an active connection to the edge.
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: "tunnel-{{ .Values.kuma.name }}-config"
          mountPath: /etc/cloudflared/config
          readOnly: true
        # Each tunnel has an associated "credentials file" which authorizes machines
        # to run the tunnel. cloudflared will read this file from its local filesystem,
        # and it'll be stored in a k8s secret.
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
      volumes:
      - name: creds
        secret:
          secretName: "tunnel-{{ .Values.kuma.name }}-credentials"
      - name: "tunnel-{{ .Values.kuma.name }}-config"
        configMap:
          name: "tunnel-{{ .Values.kuma.name }}-config"
          items:
          - key: config.yaml
            path: config.yaml
{{- end }}
{{- end }}