apiVersion: v2
name: cert-manager
description: A Helm chart for Cert Manager
type: application
version: 0.1.0
appVersion: "1.0.0"
sources:
  - https://github.com/pheliperocha/home-server
  - https://github.com/pheliperocha/home-server/tree/main/kube/cert-manager
maintainers:
  - name: Phelipe Rocha
    url: https://pheliperocha.com
dependencies:
  - name: cert-manager
    version: "1.17.1"
    repository: "https://charts.jetstack.io"
    condition: cert_manager.enabled