{{- if .Values.ingress.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ingress-loadbalancer
  namespace: ingress
spec:
  type: LoadBalancer
  selector:
    app: nginx-ingress-microk8s-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
{{- end }}