{{- if .Values.atuin.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.atuin.name }}-pv-claim
  labels:
    {{- include "atuin.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
{{- end }}