{{- if .Values.atuin.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.atuin.name }}-secrets"
type: Opaque
data:
  ATUIN_DB_URI: {{ .Values.atuin.db.dbURI | b64enc | quote }}
{{- end }}