apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tunnel: cf-tunnel
  name: cf-tunnel
  namespace: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      tunnel: cf-tunnel
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        tunnel: cf-tunnel
    spec:
      containers:
        - args:
            - tunnel
            - --no-autoupdate
            - --metrics
            - 0.0.0.0:8081
            - run
            - --token
            - $(token)
          envFrom:
            - secretRef:
                name: cf-tunnel
          env:
            - name: TZ
              value: UTC
          image: cloudflare/cloudflared:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
          name: tunnel
          ports:
            - containerPort: 8081
              name: http-metrics
---
apiVersion: v1
data:
  token: xxx
kind: Secret
metadata:
  name: cf-tunnel
  namespace: drone
type: Opaque