apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: schedule-backup
  namespace: finance-project-staging
spec:
  backend:
    s3:
      endpoint: https://s3.sa-east-1.amazonaws.com
      bucket: home-server-backups
      accessKeyIDSecretRef:
        name: k8up-secrets
        key: AWS_ACCESS_KEY_ID
      secretAccessKeySecretRef:
        name: k8up-secrets
        key: AWS_SECRET_ACCESS_KEY
    repoPasswordSecretRef:
      name: k8up-secrets
      key: RESTIC_REPOSITORY_PASSWORD
  check:
    schedule: '0 1 * * 2' # At 01:00 on Tuesday
  backup:
    schedule: '0 2 * * 2' # At 02:00 on Tuesday
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
  prune:
    schedule: '0 3 * * 2' # At 03:00 on Tuesday
    retention:
      keepLast: 5
