context_flow:
  enabled: true
  name: context-flow
  port: 3000
  ingress:
    enabled: true
    localHostname: context-flow.home.pheliperocha.com
  tunnel:
    enabled: true
  migration:
    enabled: true
  web:
    replicaCount: 1
    image: pheliperocha/home-server:context-flow-web-1.0.0
  api:
    replicaCount: 1
    image: pheliperocha/home-server:context-flow-api-1.0.0