{{- if .Values.homeassistant.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.homeassistant.name }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.homeassistant.replicaCount }}
  selector:
    matchLabels:
      {{- include "homeassistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "homeassistant.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.homeassistant.name }}
      restartPolicy: Always
      containers:
        - name: {{ .Values.homeassistant.name }}
          image: "ghcr.io/home-assistant/home-assistant:2023.3.6"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 60
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 60
            failureThreshold: 5
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /config
              name: {{ .Values.homeassistant.name }}-persistent-volume
      volumes:
        - name: {{ .Values.homeassistant.name }}-persistent-volume
          persistentVolumeClaim:
            claimName: {{ .Values.homeassistant.name }}-pv-claim
{{- end }}