apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.homeassistant.name }}-pv-claim
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
