{{- if .Values.homeassistant.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.homeassistant.name }}-service
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8123
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "homeassistant.selectorLabels" . | nindent 4 }}
{{- end }}