{{- if .Values.homeassistant.enabled }}
{{- if .Values.homeassistant.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.homeassistant.name }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
  {{- with .Values.homeassistant.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}