apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-key
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.drone_launcher.name }}-secrets"
type: Opaque
data:
  # TODO: Use a different secret for launcher
  AWS_ACCESS_KEY_ID: {{ .Values.drone_launcher.awsAccessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.drone_launcher.awsSecretAccessKey | b64enc | quote }}
  TOKEN: {{ .Values.drone_launcher.TOKEN | b64enc | quote }}
  GIT_TOKEN: {{ .Values.drone_launcher.GIT_TOKEN | b64enc | quote }}
  WEBHOOK_SECRET: {{ .Values.drone_launcher.WEBHOOK_SECRET | b64enc | quote }}
---