apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.cert_manager.cloudflare_email }}
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
      - dns01:
          cloudflare:
            email: {{ .Values.cert_manager.cloudflare_email }}
            apiTokenSecretRef:
              name: {{ .Values.cert_manager.name }}-secrets
              key: CLOUDFLARE_API_TOKEN
        selector:
          dnsZones:
            - "home.pheliperocha.com"