{{- if .Values.ntfy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ntfy.name }}-config
data:
  server.yml: |
    base-url: https://{{ .Values.ntfy.publicHostname }}
    auth-file: {{ .Values.ntfy.volumePath }}/user.db
    auth-default-access: deny-all
    cache-file: {{ .Values.ntfy.volumePath }}/cache.db
{{- end }}