apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.homeassistant.name }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8123
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "homeassistant.selectorLabels" . | nindent 4 }}